version: '3'
services:
  python:
    build: ./app
    command: sh -c "sleep 50s ; python3 ./app/app.py"
    ports:
      - '5000:5000'
    depends_on:
      - mysql

  mysql:
    build: ./db/
    restart: always
    environment:
      MYSQL_DATABASE: 'db1'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '9999:3306'